#!/bin/bash
TMPDIR=$(mktemp -d)
cd $TMPDIR
for domain in $(ls /var/vmail | grep "\."); do
        tar cf $domain.tar /var/vmail/$domain > /dev/null 2>&1
done
tar cvzf /tmp/vmail_backup.tar.gz ./*.tar > /dev/null 2>&1
rm -r $TMPDIR
echo "A gzipped tarball was created in /tmp. Perhaps."

