#!/bin/bash

if (( $EUID != 0 )); then
    echo "Please run as root"
    exit
fi

if [[ ! -z "${1##[0-9]*}" || -z $1 ]]; then
	echo "Parameter must be a value in MB."
	exit 1
fi

CONF_HTTPD_APACHE=$(grep -lir "mailcow site configuration" /etc/apache2/sites-available/)
CONF_HTTPD_NGINX=$(grep -lir "mailcow site configuration" /etc/nginx/sites-available/)
DIST_CODENAME=$(lsb_release -cs)
if [[ $DIST_CODENAME == "xenial" ]]; then
	PHPCONF="/etc/php5"
else
	PHPCONF="/etc/php/7.0"
fi

if [[ ! -z ${CONF_HTTPD_APACHE} ]]; then
        sed -i "/upload_max_filesize/c\php_admin_value upload_max_filesize ${1}M" ${CONF_HTTPD_APACHE}
        sed -i "/post_max_size/c\php_admin_value post_max_size $(expr $1 + 1)M"  ${CONF_HTTPD_APACHE}
        sed -i "s/message_size_limit.*/message_size_limit = $(( $1 * 1048576 ))/g" /etc/postfix/main.cf
        echo "Reloading services..."
        postfix reload
        service apache2 reload
elif [[ ! -z ${CONF_HTTPD_NGINX} ]]; then
	sed -i "/upload_max_filesize/c\php_admin_value[upload_max_filesize] = ${1}M" ${PHPCONF}/fpm/pool.d/mail.conf
	sed -i "/post_max_size/c\php_admin_value[post_max_size] = $(expr $1 + 1)M" ${PHPCONF}/fpm/pool.d/mail.conf
	sed -i "s/client_max_body_size.*/client_max_body_size ${1}m;/g" ${CONF_HTTPD_NGINX}
	sed -i "s/message_size_limit.*/message_size_limit = $(( $1 * 1048576 ))/g" /etc/postfix/main.cf
	echo "Reloading services..."
	postfix reload
	nginx -s reload
	service php5-fpm reload
elif [[ ! -z $(grep -ir "mailcow site configuration" /etc/apache2/sites-available/ 2> /dev/null) ]]; then
	sed -i "/upload_max_filesize/c\php_admin_value upload_max_filesize ${1}M" /etc/apache2/sites-available/mailcow.conf
	sed -i "/post_max_size/c\php_admin_value post_max_size $(expr $1 + 1)M"  /etc/apache2/sites-available/mailcow.conf
	sed -i "s/message_size_limit.*/message_size_limit = $(( $1 * 1048576 ))/g" /etc/postfix/main.cf
	echo "Reloading services..."
	postfix reload
	service apache2 reload
else
	echo "Error: cannot find site configuration"
	exit 1
fi
