#!/bin/bash
PATH=/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/bin/X11

[[ -z $1 || -z $2 ]] && echo "Usage: $0 username password" && exit 1
mailcow_admin_pass=$2
mailcow_admin_user=$1

if [[ ! -z $(mysql --host my_dbhost -u my_mailcowuser -pmy_mailcowpass my_mailcowdb -e "SELECT username FROM admin WHERE username='$mailcow_admin_user' AND superadmin='1';" -N -B) ]]; then
        mailcow_admin_pass_hashed=$(doveadm pw -s SHA512-CRYPT -p $mailcow_admin_pass)
        mysql --host my_dbhost -u my_mailcowuser -pmy_mailcowpass my_mailcowdb -e "DELETE FROM admin WHERE username='$mailcow_admin_user';"
        mysql --host my_dbhost -u my_mailcowuser -pmy_mailcowpass my_mailcowdb -e "INSERT INTO admin VALUES ('$mailcow_admin_user','$mailcow_admin_pass_hashed',1,now(),now(),1);"
else
        echo "Admin not found"
        echo
        echo "Valid usernames: "
        mysql --host my_dbhost -u my_mailcowuser -pmy_mailcowpass my_mailcowdb -e "SELECT username FROM admin where superadmin='1';" -N -B
        exit 1
fi
