#!/bin/bash
if [[ ! -z $(/bin/su debian-spamd -c "/usr/bin/sa-update --nogpg --channel spamassassin.heinlein-support.de -v | /bin/grep 'no fresh updates were available'") ]]; then
exit 0
else
/bin/su debian-spamd -c "sa-compile --quiet"
fi
