#!/bin/bash
PATH=/usr/local/bin:/usr/local/sbin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/bin/X11

for domain in $(ls /var/vmail); do
	if [[ $domain != "vfilter" && $domain != "sieve" && -d /var/vmail/$domain ]]; then
		for user in $(ls /var/vmail/$domain); do
			[[ -d "/var/vmail/$domain/$user/.Junk/cur" ]] && sa-learn --dbpath /var/lib/spamassassin/.spamassassin --no-sync --spam /var/vmail/$domain/$user/.Junk/cur > /dev/null
			[[ -d "/var/vmail/$domain/$user/cur" ]] && sa-learn --dbpath /var/lib/spamassassin/.spamassassin --no-sync --ham /var/vmail/$domain/$user/cur > /dev/null
		done
	fi
done
sa-learn --dbpath /var/lib/spamassassin/.spamassassin --sync > /dev/null
chown -R debian-spamd: /var/lib/spamassassin/.spamassassin
